import { StyleSheet } from 'react-native';

import type { SemanticColors } from '@/constants/accessibilityColors';

export function createPrivilegedLoginStyles(sem: SemanticColors) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: '#f5f5f5' },
    scroll: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
      paddingVertical: 40,
    },
    card: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: '#fff',
      borderRadius: 16,
      padding: 28,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    title: {
      fontSize: 24,
      fontWeight: '700',
      color: '#1f2937',
      textAlign: 'center',
      marginBottom: 6,
    },
    subtitle: { fontSize: 15, color: '#6b7280', textAlign: 'center', marginBottom: 24 },
    googleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      width: '100%',
      paddingVertical: 14,
      paddingHorizontal: 24,
      backgroundColor: '#fff',
      borderRadius: 0,
      borderWidth: 1,
      borderColor: '#e5e7eb',
    },
    googleIcon: { width: 22, height: 22 },
    googleButtonText: { fontSize: 16, fontWeight: '600', color: '#1f2937' },
    hintText: {
      color: '#6b7280',
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 16,
      lineHeight: 18,
    },
    errorText: { color: '#dc2626', fontSize: 14, textAlign: 'center', marginBottom: 12 },
    localForm: { width: '100%', alignSelf: 'stretch' },
    input: {
      width: '100%',
      paddingVertical: 11,
      paddingHorizontal: 14,
      fontSize: 16,
      borderWidth: 1,
      borderColor: '#e5e7eb',
      borderRadius: 10,
      marginBottom: 12,
    },
    primaryButton: {
      width: '100%',
      paddingVertical: 14,
      borderRadius: 10,
      backgroundColor: sem.accent,
      alignItems: 'center',
      marginBottom: 4,
    },
    primaryButtonText: { fontSize: 16, fontWeight: '600', color: '#fff' },
    separatorText: { marginVertical: 14, color: '#6b7280', fontSize: 14, fontWeight: '600' },
    openingGoogle: { alignItems: 'center', gap: 16, paddingVertical: 24 },
    openingGoogleText: { fontSize: 16, color: '#6b7280' },
    successBox: { alignItems: 'center', gap: 10, paddingVertical: 10 },
    successTitle: { fontSize: 18, fontWeight: '700', color: '#111827' },
    successText: { fontSize: 14, color: '#374151' },
    secondaryButton: {
      marginTop: 12,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
      backgroundColor: '#111827',
    },
    secondaryButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
    backLink: { marginTop: 20 },
    backLinkText: { fontSize: 14, color: '#6b7280' },
  });
}
