import { StyleSheet } from 'react-native';

import type { ScreenTheme } from '@/constants/screenTheme';

export function createPrivilegedLoginStyles(theme: ScreenTheme) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.panelScreenBg },
    scroll: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
      paddingVertical: 40,
    },
    card: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 28,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme.isDark ? 0.2 : 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    title: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.title,
      textAlign: 'center',
      marginBottom: 6,
    },
    subtitle: { fontSize: 15, color: theme.mutedText, textAlign: 'center', marginBottom: 24 },
    googleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      width: '100%',
      paddingVertical: 14,
      paddingHorizontal: 24,
      backgroundColor: theme.googleBtnBg,
      borderRadius: 0,
      borderWidth: 1,
      borderColor: theme.googleBtnBorder,
    },
    googleIcon: { width: 22, height: 22 },
    googleButtonText: { fontSize: 16, fontWeight: '600', color: theme.title },
    hintText: {
      color: theme.mutedText,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 16,
      lineHeight: 18,
    },
    errorText: { color: theme.error, fontSize: 14, textAlign: 'center', marginBottom: 12 },
    localForm: { width: '100%', alignSelf: 'stretch' },
    input: {
      width: '100%',
      paddingVertical: 11,
      paddingHorizontal: 14,
      fontSize: 16,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      borderRadius: 10,
      marginBottom: 12,
      backgroundColor: theme.inputBg,
      color: theme.inputText,
    },
    primaryButton: {
      width: '100%',
      paddingVertical: 14,
      borderRadius: 10,
      backgroundColor: theme.accent,
      alignItems: 'center',
      marginBottom: 4,
    },
    primaryButtonText: { fontSize: 16, fontWeight: '600', color: theme.textOnAccent },
    separatorText: { marginVertical: 14, color: theme.mutedText, fontSize: 14, fontWeight: '600' },
    openingGoogle: { alignItems: 'center', gap: 16, paddingVertical: 24 },
    openingGoogleText: { fontSize: 16, color: theme.mutedText },
    successBox: { alignItems: 'center', gap: 10, paddingVertical: 10 },
    successTitle: { fontSize: 18, fontWeight: '700', color: theme.title },
    successText: { fontSize: 14, color: theme.secondaryText },
    secondaryButton: {
      marginTop: 12,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
      backgroundColor: theme.primaryBtnBg,
    },
    secondaryButtonText: { color: theme.primaryBtnText, fontSize: 14, fontWeight: '600' },
    backLink: { marginTop: 20 },
    backLinkText: { fontSize: 14, color: theme.mutedText },
  });
}
